//! C ABI the Basecamp module calls.
//!
//! Both modules under `generated/` come from `spel-client-gen` and are regenerated by
//! `scripts/generate-basecamp-ffi.sh`; they are committed so the library builds without the
//! generator present, and they must not be edited by hand.

pub mod generated;
