// Started from spel-client-gen --target logos-module, then rewritten twice — see the history below,
// because both rewrites were forced by facts about Logos Basecamp that are written down nowhere.
//
// ── 1. The plugin, not an inner object, carries the API ────────────────────────────────────────
//
// A `ui_qml` module is loaded twice over. The dylib goes into a `ui-host` child process, which calls
// initLogos and then publishes *this object* over QtRemoteObjects under the module's name. The QML
// named by the manifest's `view` is loaded by the **main** Basecamp process, in an engine this
// plugin never touches — so a context property set on our own QQuickWidget was invisible where the
// QML actually ran, and every binding raised "backend is not defined" behind a window that drew
// perfectly.
//
// ── 2. And the API has to be generated, not hand-declared ──────────────────────────────────────
//
// The QML reaches this object as `logos.module("private_multisig")`, and Basecamp builds that
// replica through a *factory* plugin loaded beside this one (src/ReplicaFactory.cpp). The first
// factory handed back a **dynamic** replica; Basecamp crashed on opening the module. Both modules
// that do work inside it — Basecamp's own package_manager_ui and the official logos_delivery_demo —
// inherit a `…SimpleSource` generated by `repc` from a `.rep` file and hand out the matching typed
// replica. So this class inherits ours, from app/private_multisig.rep.
//
// The consequence worth knowing: the remote API is defined in that .rep, not here. This class only
// implements its slots, and pushes values into it as the backend changes. Adding a property means
// editing the .rep — and QtRemoteObjects matches the two sides by a signature over that file, so
// they cannot drift apart without failing to pair.
#pragma once

#include <QObject>
#include <QWidget>
#include <QtPlugin>

#include "rep_private_multisig_source.h"

class LogosAPI;
class PrivateMultisigBackend;

class IComponent {
public:
	virtual ~IComponent() = default;
	virtual QWidget* createWidget(LogosAPI* api = nullptr) = 0;
	virtual void     destroyWidget(QWidget* widget) = 0;
};
#define IComponent_iid "com.logos.component.IComponent"
Q_DECLARE_INTERFACE(IComponent, IComponent_iid)

class PrivateMultisigPlugin : public PrivateMultisigSimpleSource, public IComponent {
	Q_OBJECT
	Q_PLUGIN_METADATA(IID IComponent_iid FILE "../manifest.json")
	Q_INTERFACES(IComponent)

public:
	explicit PrivateMultisigPlugin(QObject* parent = nullptr);
	~PrivateMultisigPlugin() override;

	Q_INVOKABLE void initLogos(LogosAPI* api);

	QWidget* createWidget(LogosAPI* api = nullptr) override;
	void     destroyWidget(QWidget* widget) override;

	// ── The .rep's slots ─────────────────────────────────────────────────
	//
	// The four setters are also the generated property setters, so overriding them is what keeps a
	// write from the UI going through the backend — which persists it — instead of only updating
	// the replicated copy.
	void setWalletPath(QString v) override;
	void setSequencerUrl(QString v) override;
	void setProgramIdHex(QString v) override;
	void setWalletCliDir(QString v) override;

	void createMultisig(QString creatorId, QString configHash, QString memberRoot, quint32 m, quint32 n, QString multisigId, QVariantList membershipProgramId) override;
	void createProposal(QString proposerId, QString configHash, QString proposalSeed, QString proposalId, QString recipient, QString amount) override;
	void approve(QString configHash, QString proposalSeed, QString memberRoot, QString claimedNullifier, QVariantList witness) override;
	void execute(QString configHash, QString proposalSeed) override;

	void fetchConfig(QString configHash) override;
	void fetchProposal(QString proposalSeed) override;

	void checkConnection() override;
	void listAccounts() override;
	void createAccount(QString label) override;
	void inspectAccount(QString accountId) override;
	void decodeAccount(QString accountId) override;
	void saveHistory(QString key, QString value) override;

private:
	// Creates the backend on first use and mirrors every one of its changes into the replicated
	// properties, so a replica in the main process sees exactly what the widget would.
	PrivateMultisigBackend* backend() const;

	LogosAPI*                       m_api     = nullptr;
	mutable PrivateMultisigBackend* m_backend = nullptr;
};
