// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
#include "PrivateMultisigBackend.h"

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMetaObject>
#include <QSettings>
#include <QThreadPool>
#include <QTimer>
#include <QThreadPool>

extern "C" {
    char* private_multisig_create_multisig(const char* args_json);
    char* private_multisig_create_proposal(const char* args_json);
    char* private_multisig_approve(const char* args_json);
    char* private_multisig_execute(const char* args_json);
    char* private_multisig_fetch_config(const char* args_json);
    char* private_multisig_fetch_proposal(const char* args_json);
    char* private_multisig_program_id();
    void  private_multisig_free_string(char* s);
    char* private_multisig_check_connection(const char* args_json);
    char* private_multisig_inspect_account(const char* args_json);
    char* private_multisig_list_accounts(const char* args_json);
    char* private_multisig_create_account(const char* args_json);
    char* private_multisig_decode_account(const char* args_json);
}

// ── Construction ──────────────────────────────────────────────────────────

PrivateMultisigBackend::PrivateMultisigBackend(LogosAPI* /*api*/, QObject* parent)
    : QObject(parent)
{
    QSettings s("logos-co", "private_multisig");
    m_walletPath   = s.value("walletPath",   qEnvironmentVariable("LEE_WALLET_HOME_DIR",  ".scaffold/wallet")).toString();
    m_sequencerUrl = s.value("sequencerUrl", qEnvironmentVariable("NSSA_SEQUENCER_URL",   "http://127.0.0.1:3040")).toString();
    m_programIdHex = s.value("programIdHex", qEnvironmentVariable("PRIVATE_MULTISIG_PROGRAM_ID")).toString();
    // The wallet pages shell out to LEZ's `wallet` binary, which the C ABI resolves through PATH.
    // Basecamp starts its module hosts with the desktop session's PATH, which does not include a
    // LEZ build tree, so those pages failed with "No such file or directory (os error 2)" and no
    // hint of what was missing. This is the directory that holds it.
    m_walletCliDir = s.value("walletCliDir", qEnvironmentVariable("PMSIG_WALLET_CLI_DIR")).toString();
    applyWalletCliDir();
    if (m_programIdHex.isEmpty()) {
        char* raw = private_multisig_program_id();
        if (raw) {
            m_programIdHex = QJsonDocument::fromJson(QByteArray(raw))
                                 .object().value("program_id_hex").toString();
            private_multisig_free_string(raw);
        }
    }
    // Pre-populate account list so field pickers have data before wallet page is visited.
    if (!m_walletPath.isEmpty())
        QTimer::singleShot(0, this, [this] { listAccounts(); });
}

PrivateMultisigBackend::~PrivateMultisigBackend() = default;

// ── Configuration ────────────────────────────────────────────────────────

// Puts the configured directory at the front of this process's PATH, so the C ABI's
// `Command::new("wallet")` finds the binary the operator pointed at rather than whatever the
// desktop session happens to have. Prepending, not replacing: the rest of PATH still works.
// "wallet CLI: No such file or directory (os error 2)" names neither the binary nor the setting
// that would fix it. Every wallet page fails this way on a machine that has not built LEZ, which is
// every machine Basecamp runs on by default.
static QString explain(const QString& error) {
    if (error.contains(QLatin1String("wallet CLI:"))
        && error.contains(QLatin1String("No such file"))) {
        return QStringLiteral(
            "%1 — the wallet pages run LEZ's `wallet` binary, and it is not on this process's PATH. "
            "Set \"Wallet CLI directory\" in Settings to the directory holding it (a LEZ checkout's "
            "target/release), or start Basecamp from a shell where `wallet` is on PATH.")
            .arg(error);
    }
    return error;
}

void PrivateMultisigBackend::applyWalletCliDir() {
    if (m_walletCliDir.isEmpty()) return;
    const QByteArray current = qgetenv("PATH");
    const QByteArray wanted  = m_walletCliDir.toLocal8Bit();
    if (current.split(':').contains(wanted)) return;
    qputenv("PATH", wanted + ':' + current);
}

void PrivateMultisigBackend::setWalletCliDir(const QString& v) {
    if (m_walletCliDir == v) return;
    m_walletCliDir = v;
    QSettings("logos-co", "private_multisig").setValue("walletCliDir", v);
    applyWalletCliDir();
    emit walletCliDirChanged();
    if (!m_walletPath.isEmpty()) listAccounts();
}

void PrivateMultisigBackend::setWalletPath(const QString& v) {
    if (m_walletPath == v) return;
    m_walletPath = v;
    QSettings("logos-co", "private_multisig").setValue("walletPath", v);
    emit walletPathChanged();
    if (!v.isEmpty()) listAccounts();
}

void PrivateMultisigBackend::setSequencerUrl(const QString& v) {
    if (m_sequencerUrl == v) return;
    m_sequencerUrl = v;
    QSettings("logos-co", "private_multisig").setValue("sequencerUrl", v);
    emit sequencerUrlChanged();
}

void PrivateMultisigBackend::setProgramIdHex(const QString& v) {
    if (m_programIdHex == v) return;
    m_programIdHex = v;
    QSettings("logos-co", "private_multisig").setValue("programIdHex", v);
    emit programIdHexChanged();
}

// ── Helpers ──────────────────────────────────────────────────────────────

QJsonObject PrivateMultisigBackend::baseArgs() const {
    return QJsonObject{
        {"wallet_path",    m_walletPath},
        {"sequencer_url",  m_sequencerUrl},
        {"program_id_hex", m_programIdHex},
    };
}

QString PrivateMultisigBackend::callFfi(FfiFn fn, const QJsonObject& args) {
    QByteArray json = QJsonDocument(args).toJson(QJsonDocument::Compact);
    char* raw = fn(json.constData());
    if (!raw) return R"({"success":false,"error":"null return from FFI"})";
    QString result = QString::fromUtf8(raw);
    private_multisig_free_string(raw);
    return result;
}

void PrivateMultisigBackend::dispatchFfi(const QString& operation, std::function<QString()> fn) {
    if (m_busy) return;
    m_busy = true;
    emit busyChanged();

    // Deliberately not QtConcurrent. Basecamp ships QtCore, QtGui, QtQml, QtQuick, QtWidgets and
    // dozens more in its own Frameworks directory — but not QtConcurrent, and a plugin that links a
    // framework the host does not have cannot be loaded at all. That is why the module installed
    // and then never appeared: the ui_qml path loads the plugin, and loading failed.
    //
    // QThreadPool is in QtCore and does the same job here: run the call off the UI thread, deliver
    // the result back on it.
    QThreadPool::globalInstance()->start([this, operation, fn]() {
        const QString result = fn();
        QMetaObject::invokeMethod(
            this,
            [this, operation, result]() {
                handleFfiResult(operation, result);
                m_busy = false;
                emit busyChanged();
            },
            Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::handleFfiResult(const QString& operation, const QString& result) {
    QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();

    if (!obj.value("success").toBool()) {
        m_lastError = explain(obj.value("error").toString(result));
        emit lastErrorChanged();
        emit operationError(operation, m_lastError);
        return;
    }

    m_lastError.clear();
    emit lastErrorChanged();

    m_lastResult = obj.toVariantMap();
    emit lastResultChanged();

    if (obj.contains("tx_hash")) {
        m_lastTxHash = obj.value("tx_hash").toString();
        emit lastTxHashChanged();
        emit operationSuccess(operation, m_lastTxHash);
    } else {
        emit operationSuccess(operation, QString());
    }
}

// ── Instructions ─────────────────────────────────────────────────────────

void PrivateMultisigBackend::createMultisig(const QString& creatorId, const QString& configHash, const QString& memberRoot, quint32 m, quint32 n, const QString& multisigId, const QVariantList& membershipProgramId) {
    QJsonObject args = baseArgs();
    args["creator"] = creatorId;
    args["config_hash"] = configHash;
    args["member_root"] = memberRoot;
    args["m"] = static_cast<int>(m);
    args["n"] = static_cast<int>(n);
    args["multisig_id"] = multisigId;
    // A ProgramId is [u32; 8] and arrives as a QVariantList, which QJsonObject::operator[] will
    // not take — there is no implicit conversion to QJsonValue. spel-client-gen emits this
    // conversion for a Vec<u8> parameter (see `witness` in approve, below) but not for a
    // fixed-size array, so this was the one call in the file that could not compile. It never
    // showed up because the plugin had never been built.
    {
        QJsonArray _arr;
        for (const QVariant& _v : membershipProgramId) _arr.append(QJsonValue::fromVariant(_v));
        args["membership_program_id"] = _arr;
    }
    dispatchFfi("create_multisig", [this, args]() {
        return callFfi(private_multisig_create_multisig, args);
    });
}

void PrivateMultisigBackend::createProposal(const QString& proposerId, const QString& configHash, const QString& proposalSeed, const QString& proposalId, const QString& recipient, const QString& amount) {
    QJsonObject args = baseArgs();
    args["proposer"] = proposerId;
    args["config_hash"] = configHash;
    args["proposal_seed"] = proposalSeed;
    args["proposal_id"] = proposalId;
    args["recipient"] = recipient;
    args["amount"] = amount;
    dispatchFfi("create_proposal", [this, args]() {
        return callFfi(private_multisig_create_proposal, args);
    });
}

// This module cannot submit an approval, and must not try.
//
// The generated C ABI builds every instruction into a `PublicTransaction`. That is right for
// create, propose and execute, which are public by design. It is wrong for `approve` twice over:
// the program has no public approve path, so the chain would reject it — and the witness this
// panel would carry is the member's own secret material. Broadcasting it publicly is the exact
// failure this prize is about, and a rejected transaction is broadcast all the same.
//
// An approval is a privacy-preserving transaction whose validity depends on LEZ's circuit
// verifying the multisig program and the chained membership program. Producing one takes the
// prover, not a thin client: see `crates/sdk/examples/wallet_member.rs`. So this refuses, and says
// what to run instead, rather than leaving a button that leaks.
void PrivateMultisigBackend::approve(const QString&, const QString&, const QString&, const QString&,
                                     const QVariantList&) {
    m_lastError = QStringLiteral(
        "This module cannot submit approvals. An approval is a privacy-preserving transaction — the "
        "proof takes about 20 minutes and the witness is the member's secret material, which a "
        "public transaction would publish. Produce it with the SDK instead:\n\n"
        "    cargo run --release --example wallet_member -- approve\n\n"
        "The panels here read the result back from the chain once it lands.");
    emit lastErrorChanged();
    emit operationError(QStringLiteral("approve"), m_lastError);
}

void PrivateMultisigBackend::execute(const QString& configHash, const QString& proposalSeed) {
    QJsonObject args = baseArgs();
    args["config_hash"] = configHash;
    args["proposal_seed"] = proposalSeed;
    dispatchFfi("execute", [this, args]() {
        return callFfi(private_multisig_execute, args);
    });
}

// ── Fetch ────────────────────────────────────────────────────────────────

// A fetch that finds nothing is a failure, not an empty success.
//
// `fetch_*` report success as long as the RPC answered, and hand back an empty state when the
// account holds no bytes or does not decode. Reporting that as success left the panel showing its
// "No data — press \u21bb to fetch" placeholder with no way to tell an empty account from a
// misconfigured sequencer, an unknown program id, or a mistyped hash — the three things that
// actually go wrong. Each now names itself in lastError.
void PrivateMultisigBackend::applyFetched(const QString& what,
                                          const QString& result,
                                          QVariantMap& target,
                                          void (PrivateMultisigBackend::*changed)()) {
    const QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
    if (!obj.value("success").toBool()) {
        m_lastError = explain(obj.value("error").toString(result));
        emit lastErrorChanged();
        emit operationError("fetch_" + what, m_lastError);
        return;
    }
    const QVariantMap state = obj.value("state").toObject().toVariantMap();
    if (state.isEmpty()) {
        m_lastError = QStringLiteral(
            "no %1 account at that address. Check the %1 hash, and that Settings names the "
            "sequencer and program id this multisig was deployed to (Settings holds \"%2\" and "
            "program %3).")
            .arg(what, m_sequencerUrl,
                 m_programIdHex.isEmpty() ? QStringLiteral("(unset)") : m_programIdHex);
        m_fetchErrors[what] = m_lastError;
        emit fetchErrorsChanged();
        emit lastErrorChanged();
        emit operationError("fetch_" + what, m_lastError);
        return;
    }
    target = state;
    (this->*changed)();
    m_fetchErrors.remove(what);
    emit fetchErrorsChanged();
    m_lastError.clear();
    emit lastErrorChanged();
}


void PrivateMultisigBackend::fetchConfig(const QString& configHash) {
    QJsonObject args = baseArgs();
    args["config_hash"] = configHash;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_fetch_config, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            applyFetched("config", result, m_config, &PrivateMultisigBackend::configChanged);
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::fetchProposal(const QString& proposalSeed) {
    QJsonObject args = baseArgs();
    args["proposal_seed"] = proposalSeed;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_fetch_proposal, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            applyFetched("proposal", result, m_proposal, &PrivateMultisigBackend::proposalChanged);
        }, Qt::QueuedConnection);
    });
}

// ── Wallet ──────────────────────────────────────────────────────────────

void PrivateMultisigBackend::checkConnection() {
    QJsonObject args = baseArgs();
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_check_connection, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                m_connectionStatus = "\u2713 " + obj.value("sequencer_url").toString();
            } else {
                m_connectionStatus = "\u2717 " + obj.value("error").toString(result);
            }
            emit connectionStatusChanged();
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::listAccounts() {
    QJsonObject args = baseArgs();
    args["program_id_hex"] = m_programIdHex;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_list_accounts, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                QVariantList list;
                for (const QJsonValue& v : obj.value("accounts").toArray()) {
                    QJsonObject ao = v.toObject();
                    QVariantMap item;
                    item["id"]     = ao.value("id").toString();
                    item["label"]  = ao.value("label").toString();
                    item["path"]   = ao.value("path").toString();
                    item["status"] = ao.value("status").toString();
                    list.append(item);
                }
                m_walletAccounts = list;
                emit walletAccountsChanged();
            } else {
                m_lastError = explain(obj.value("error").toString(result));
                emit lastErrorChanged();
            }
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::createAccount(const QString& label) {
    QJsonObject args = baseArgs();
    if (!label.isEmpty()) args["label"] = label;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_create_account, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                QString newId = obj.value("account_id").toString();
                emit operationSuccess("create_account", newId);
                listAccounts();
            } else {
                m_lastError = explain(obj.value("error").toString(result));
                emit lastErrorChanged();
                emit operationError("create_account", m_lastError);
            }
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::inspectAccount(const QString& accountId) {
    QJsonObject args = baseArgs();
    args["account_id"] = accountId;
    args["program_id_hex"] = m_programIdHex;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_inspect_account, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                QVariantMap info;
                info["status"]          = obj.value("status").toString();
                info["data_len"]        = obj.value("data_len").toInt();
                info["data_preview"]    = obj.value("data_preview").toString();
                info["program_owner"]   = obj.value("program_owner").toString();
                info["has_signing_key"] = obj.value("has_signing_key").toBool() ? "yes" : "no";
                m_walletAccountInfo = info;
            } else {
                QVariantMap info;
                info["error"] = obj.value("error").toString();
                m_walletAccountInfo = info;
            }
            emit walletAccountInfoChanged();
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::decodeAccount(const QString& accountId) {
    QJsonObject args = baseArgs();
    args["account_id"] = accountId;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_decode_account, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                QVariantMap decoded;
                decoded["type"] = obj.value("type").toString();
                if (!obj.value("fields").isNull()) {
                    QJsonObject fields = obj.value("fields").toObject();
                    QVariantMap fmap;
                    for (auto it = fields.begin(); it != fields.end(); ++it)
                        fmap[it.key()] = it.value().toVariant();
                    decoded["fields"] = fmap;
                }
                if (!obj.value("raw_hex").isNull())
                    decoded["raw_hex"] = obj.value("raw_hex").toString();
                if (!obj.value("status").isNull())
                    decoded["status"] = obj.value("status").toString();
                m_walletDecodedAccount = decoded;
            } else {
                m_walletDecodedAccount = {{ {"error", obj.value("error").toString()} }};
            }
            emit walletDecodedAccountChanged();
        }, Qt::QueuedConnection);
    });
}

// ── Field history ────────────────────────────────────────────────────────

QStringList PrivateMultisigBackend::fieldHistory(const QString& key) const {
    return QSettings("logos-co", "private_multisig")
               .value("history/" + key, QStringList{}).toStringList();
}

void PrivateMultisigBackend::saveHistory(const QString& key, const QString& value) {
    if (value.trimmed().isEmpty()) return;
    QSettings s("logos-co", "private_multisig");
    QStringList h = s.value("history/" + key, QStringList{}).toStringList();
    h.removeAll(value);
    h.prepend(value);
    if (h.size() > 10) h.resize(10);
    s.setValue("history/" + key, h);
}

