// Nothing to see: `qt6_add_repc_sources` needs a target to attach the generated source to, and a
// CMake library needs at least one translation unit. Both the plugin and the standalone preview app
// link this one so repc runs once — generating it per target makes CMake collide on the moc output
// ("Files to be generated by multiple different commands").
