// The piece Basecamp needs to hand this module's backend to its QML.
//
// A `ui_qml` module runs in two processes: the plugin in a `ui-host` child, which publishes it over
// QtRemoteObjects, and the QML in Basecamp's main process. `logos.module("private_multisig")` is how
// the QML asks for the far side — and the bridge cannot build that replica by itself. It loads a
// second plugin, beside the first and named for the module, and asks *it* to construct one:
//
//     LogosQmlBridge: no replica factory plugin registered for "private_multisig"
//
// which is what our log said while every panel sat inert. Basecamp's own package_manager_ui ships
// exactly this, as `package_manager_ui_replica_factory.dylib`.
//
// ── The interface, and why it is declared here ─────────────────────────────────────────────────
//
// Basecamp ships no headers, so `LogosViewReplicaFactory` is reconstructed from the binary rather
// than guessed at. Its IID is the string the host looks for; its shape was read out of the
// reference plugin's vtable:
//
//     vtable @0x14358 -> acquire(QRemoteObjectNode*)
//     vtable @0x14360 -> replicaMetaObject() const
//     …offset-to-top, typeinfo…                     ← the secondary sub-vtable starts here
//     vtable @0x14388 -> thunk to acquire
//     vtable @0x14390 -> thunk to replicaMetaObject
//
// The secondary sub-vtable begins *directly* with the thunk to `acquire`: there are no destructor
// slots ahead of it, so the interface declares no virtual destructor, and `acquire` precedes
// `replicaMetaObject`. Both details matter — a mismatched vtable does not fail to compile, it calls
// the wrong function through a garbage pointer in the host's own process.
#include <QMetaObject>
#include <QObject>
#include <QRemoteObjectDynamicReplica>
#include <QRemoteObjectNode>
#include <QtPlugin>

class LogosViewReplicaFactory {
public:
	virtual QObject*           acquire(QRemoteObjectNode* node)  = 0;
	virtual const QMetaObject* replicaMetaObject() const         = 0;
};

#define LogosViewReplicaFactory_iid "logos.view.replica_factory/1.0"
Q_DECLARE_INTERFACE(LogosViewReplicaFactory, LogosViewReplicaFactory_iid)

class PrivateMultisigReplicaFactory : public QObject, public LogosViewReplicaFactory {
	Q_OBJECT
	Q_PLUGIN_METADATA(IID LogosViewReplicaFactory_iid)
	Q_INTERFACES(LogosViewReplicaFactory)

public:
	// A *dynamic* replica, not one generated by repc from a .rep file.
	//
	// The source side is whatever `ui-host` published from the plugin's own metaobject. A typed
	// replica would have to mirror that exactly — every property, signal and slot, in order — and
	// QtRemoteObjects rejects the pair on any mismatch, at runtime, with the module looking simply
	// broken. A dynamic replica is built *from* the source's metaobject when it arrives, so the two
	// cannot drift apart: the backend's API is defined in one place, PrivateMultisigPlugin, and this
	// file never needs editing when it changes.
	//
	// The cost is that the object is empty until the source connects. That is already how the QML
	// treats it — `logos.module()` yields a replica, so a property read is a cached value and a call
	// is a message — and property changes arrive as the replica initialises.
	QObject* acquire(QRemoteObjectNode* node) override {
		if (!node) return nullptr;
		return node->acquireDynamic(QStringLiteral("private_multisig"));
	}

	// Nothing static to describe: a dynamic replica's real metaobject is built at runtime, and QML
	// reads properties through the instance's own `metaObject()` rather than this.
	const QMetaObject* replicaMetaObject() const override {
		return &QRemoteObjectDynamicReplica::staticMetaObject;
	}
};

#include "ReplicaFactory.moc"
