// The piece Basecamp needs to hand this module's backend to its QML.
//
// A `ui_qml` module runs in two processes: the plugin in a `ui-host` child, which publishes it over
// QtRemoteObjects, and the QML in Basecamp's main process. `logos.module("private_multisig")` is how
// the QML asks for the far side — and the bridge cannot build that replica by itself. It loads a
// second plugin, beside the first and named for the module, and asks *it* to construct one:
//
//     LogosQmlBridge: no replica factory plugin registered for "private_multisig"
//
// which is what our log said while every panel sat inert. Basecamp's own package_manager_ui ships
// exactly this, as `package_manager_ui_replica_factory.dylib`.
//
// ── The interface, and why it is declared here ─────────────────────────────────────────────────
//
// Basecamp ships no headers, so `LogosViewReplicaFactory` is reconstructed from the binary rather
// than guessed at. Its IID is the string the host looks for; its shape was read out of the
// reference plugin's vtable:
//
//     @0x14368 -> offset-to-top
//     @0x14370 -> typeinfo                          ← the secondary sub-vtable starts here
//     @0x14378 -> thunk to ~PackageManagerUiReplicaFactoryPlugin()   (D1)
//     @0x14380 -> thunk to ~PackageManagerUiReplicaFactoryPlugin()   (D0)
//     @0x14388 -> thunk to acquire(QRemoteObjectNode*)
//     @0x14390 -> thunk to replicaMetaObject() const
//
// So the interface declares a **virtual destructor**, and it comes first: two slots before
// `acquire`. Getting that wrong is not a compile error — the host calls what it believes is
// `acquire` at slot 2 and lands wherever slot 2 happens to be. The first version of this file
// omitted the destructor, and Basecamp died with
//
//     0  ???             vtable for __cxxabiv1::__class_type_info + 16
//     1  main_ui.dylib   LogosQmlBridge::module(QString const&) + 320
//
// — an instruction fetch from the middle of libc++abi's RTTI data, two slots off, in the host's own
// process. `scripts/check-basecamp-contract.sh` now compares our vtable against the reference's so
// this cannot drift again.
#include <QMetaObject>
#include <QObject>
#include <QRemoteObjectNode>
#include <QtPlugin>

#include "LogosViewReplicaFactory.h"
#include "rep_private_multisig_replica.h"

// The interface itself lives in one header, included by the test too — see the note there.

class PrivateMultisigReplicaFactory : public QObject, public LogosViewReplicaFactory {
	Q_OBJECT
	Q_PLUGIN_METADATA(IID LogosViewReplicaFactory_iid)
	Q_INTERFACES(LogosViewReplicaFactory)

public:
	// A *typed* replica, generated by repc from app/private_multisig.rep — the same shape both
	// modules that work inside Basecamp use (its own package_manager_ui, and the official
	// logos_delivery_demo, whose factory exports a `LogosDeliveryDemoReplica`).
	//
	// The first version of this file acquired a *dynamic* replica instead. It was the smaller change
	// and it looked safer — a dynamic replica is built from whatever the source publishes, so the
	// two cannot disagree — but opening the module killed Basecamp, in the host's own QML url
	// interceptor. Matching the working reference is worth more than an argument about which design
	// ought to be safe.
	//
	// The name is the module's, not the class's: `ui-host` publishes this object as
	// "private_multisig", and a replica acquired under any other name never pairs.
	QObject* acquire(QRemoteObjectNode* node) override {
		if (!node) return nullptr;
		return node->acquire<PrivateMultisigReplica>(QStringLiteral("private_multisig"));
	}

	const QMetaObject* replicaMetaObject() const override {
		return &PrivateMultisigReplica::staticMetaObject;
	}
};

#include "ReplicaFactory.moc"
